<?php
/**
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *
 * @license GPL 2.0
 * @package Comwrap/Pdf/Templates
 * @author Thomas Spigel <tspigel@comwrap.com>
 * @version 1.0
 *
 * @var $this Comwrap_Pdf_Block_Shipment
 */
$imageUrl = Mage::getStoreConfig('sales/identity/logo', $store);
if ($imageUrl) {
    $image = Mage::getBaseUrl('media') . '/sales/store/logo/' . $image;
}
$i = 0;
?>

<head>
	<style type="text/css">
		body {
			font-size: 12px;
			font-family: "linlibertine";
		}
		table
		{
			border-collapse: collapse;
			width: 100%;
			border: 1px solid #737373;
			padding: 0;
		}
		table tr:first-child td:first-child { border-left: 0; border-top: 0; padding:5px 10px;}
		table td
		{
			padding: 10px;
		}
		.border-right
		{
			border-right: 1px solid #737373;
		}
		.border-bottom
		{
			border-bottom: 1px solid #737373;
		}
		.header table td
		{
			font-size: 11px;
			padding: 1px;
			color: white;
		}
		.no-border
		{
			border: 0;
		}
		thead tr th
		{
			font-weight: bold;
			padding: 10px;
		}
		#track td, #track th
		{
			padding: 1px 80px 1px 5px;
			font-size: 12px;
		}

		.products td {
			padding: 6px;
			height: 10px;
		}

		.products-head {
			padding: 6px !important;
			height: 10px;

		}

		.products-head td {
			font-weight: normal !important;
			padding: 6px !important;
			height: 10px;
		}
	</style>
</head>
<body>

<?php /* @var $_shipment Mage_Sales_Model_Order_Shipment */ ?>
<?php foreach($this->getShipment() as $_shipment):?>
	<?php $this->startEmulateEnvironment($_shipment->getStoreId());?>
	<?php if($i > 0) : ?>
		<pagebreak />
	<?php endif;?>
	<?php

    $this->setOrder($_shipment->getOrder());
    $_date = new Zend_Date($_shipment->getOrder()->getCreatedAt());

	?>


	<?php if($imageUrl): ?>
    <div>
	    <div style="float: left; padding-bottom: 3mm"><img width="2.6in" src="<?php echo $image?>" /></div>
    </div>
	<?php endif;?>

    <table cellpadding="0" cellspacing="0">
        <tr style="background-color: #737373;">
            <td class="header" colspan="2">
				<table>
					<tr>
						<td><?php echo $this->__('Packingslip # ')?></td>
						<td><?php echo $_shipment->getIncrementId()?></td>
					</tr>
					<tr>
						<td><?php echo $this->__('Order # ')?></td>
						<td><?php echo $_shipment->getOrder()->getIncrementId()?></td>
					</tr>
					<tr>
						<td><?php echo $this->__('Order Date: ')?></td>
						<td><?php echo $_date->get(Mage::app()->getLocale()->getDateFormat('medium'));?></td>
					</tr>
				</table>
            </td>
        </tr>
	    <tr style="background-color: #eeebeb">
		    <th style="padding: 10px; text-align: left; width: 50%" class="border-bottom border-right"><?php echo $this->__('Sold to:'); ?></th>
		    <th style="padding: 10px; text-align: left; width: 50%" class="border-bottom"><?php echo $this->__('Ship to:'); ?></th>
	    </tr>
	    <tr>
		    <td><p class="address-info"><?php echo $_shipment->getBillingAddress()->format('html');?></p></td>
		    <td><p class="address-info"><?php echo $_shipment->getShippingAddress()->format('html');?></p></td>
	    </tr>
    </table>
	<br/>
	<table cellpadding="0" cellspacing="0">
		<thead>
		<tr style="background-color: #eeebeb; border: 1px solid #737373;">
			<th class="border-bottom border-right" style="text-align: left; width: 50%;"><?php echo $this->__('Payment Method: '); ?></th>
			<th class="border-bottom" style="text-align: left; width: 50%;"><?php echo $this->__('Shipping Method: '); ?></th>
		</tr>
		</thead>
	    <tbody>
	        <tr>
	            <td style="vertical-align: top"><?php echo $this->getChildHtml('order_payment'); ?></td>
		        <td style="vertical-align: top;">
	                <?php if ($_shipment->getOrder()->getShippingDescription()): ?>
	                    <?php echo $this->escapeHtml($_shipment->getOrder()->getShippingDescription()) ?>

	                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
	                        <?php $_excl = $this->displayShippingPriceInclTax($_shipment->getOrder()); ?>
	                    <?php else: ?>
	                        <?php $_excl = $this->helper('adminhtml/sales')->displayPriceAttribute($_shipment->getOrder(), 'shipping_amount', false, ' '); ?>
	                    <?php endif; ?>
	                    <?php $_incl = $this->displayShippingPriceInclTax($_shipment->getOrder()); ?>

		                <br/>(<?php echo $this->helper('sales')->__('Total Shipping Charges');?> <?php echo $_excl?>)

	                    <?php if($_shipment->getTracksCollection()->count()): ?>
	                        <br /><br />
	                        <table id="track" class="no-border" cellpadding="0" cellspacing="0">
	                            <tr style="background-color: #eeebeb">
	                                <th style="border: 1px solid #737373; border-right: 0;"><?php echo $this->__('Title'); ?></th>
	                                <th style="border: 1px solid #737373;"><?php echo $this->__('Number'); ?></th>
	                            </tr>
	                            <?php foreach($_shipment->getTracksCollection() as $track): ?>
	                            <tr>
	                                <td><?php echo $track->getTitle() ?></td>
	                                <td><?php echo $track->getNumber() ?></td>
	                            </tr>
	                            <?php endforeach; ?>
	                        </table>
	                    <?php endif; ?>
	                <?php else: ?>
	                    <?php echo $this->helper('sales')->__('No shipping information available'); ?>
	                <?php endif; ?>
	            </td>
	        </tr>
	    </tbody>
    </table>
    <br/>
    <br/>
    <table class="no-border products" cellpadding="0" cellspacing="0">
        <thead>
        <tr class="products-head" style="background-color: #eeebeb">
            <td style="border: 1px solid #737373; border-right: 0;"><?php echo $this->__('Qty'); ?></td>
            <td style="border: 1px solid #737373; border-left: 0; border-right: 0; border-left: 0;"><?php echo $this->__('Products'); ?></td>
            <td style="border: 1px solid #737373; border-left: 0;"><?php echo $this->__('SKU'); ?></td>
        </tr>
        </thead>
        <tbody>
        <?php foreach($_shipment->getAllItems() as $_item): ?>
	        <?php if($continue) {
		        $continue = false;
		        continue;
	        } ?>
	        <tr>
		        <td><?php echo (int) $_item->getQty() ?></td>

		        <?php $productOptions = $_item->getOrderItem()->getProductOptions();
		        if(!empty($productOptions['attributes_info'])):?>
			        <?php $continue = true;?>
			        <td>
				        <?php echo $_item->getName();?>
				        <?php foreach($productOptions['attributes_info'] as $productOption):?>
					        <br />
					        <span class="product-options">
								<i><?php echo $productOption['label']?></i><br />
								&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $productOption['value'];?>
							</span>
				        <?php endforeach;?>
			        </td>
		        <?php else: ?>
			        <td><?php echo $_item->getName() ?></td>
		        <?php endif;?>
	            <td><?php echo $_item->getSku() ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
	<?php ++$i;?>
	<?php $this->stopEmulateEnvironment();?>
<?php endforeach;?>
</body>
